### PR TITLE
[C-Api] handle flexible tensor

### PR DESCRIPTION
**Pull request by jaeyun-jung**
In flexible tensor stream, sink and src handle cannot set exact tensor info from pad caps.
To handle flex-tensor, ignore tensor info while configuring the element handle.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
Requires nnstreamer PR https://github.com/nnstreamer/nnstreamer/pull/3212

**Review by myungjoo — APPROVED** [review]
LGTM

**Comment by myungjoo** [comment]
Do you need additional modifications for the stream type consolidation? https://github.com/nnstreamer/nnstreamer/issues/3351

**Comment by jaeyun-jung** [comment]
@myungjoo we need changing mime-type in testcases later. IMO, updating API code is unnecessary after implementing https://github.com/nnstreamer/nnstreamer/issues/3351.

**Review by myungjoo — APPROVED** [review]

**Pull request merged**
