### PR TITLE
[C-Api/Service] define API for ml-resource

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Define new API set for ml-resource control.

### CODE REVIEW

**Comment by songgot** [comment]
Do resources need version control?

**Comment by songgot** [comment]
> Do we need resources for version control?
As I said in the offline meeting,
Currently, data version management is not performed, and data will be replaced. Thank you.

**Comment by songgot** [comment]
No typos were found in the documentation.

**Review by songgot — APPROVED** [review]
Current concepts look good to me.

**Comment by jaeyun-jung** [comment]
Waiting for previous PR #357 - information list handle.

**Review by songgot — APPROVED** [review]
The current version is looking good to me.

**Comment by jaeyun-jung** [comment]
Waiting for other PR #357 - ml-information handle.

**Review by anyj0527 — APPROVED** [review]
LGTM👍

**Review by myungjoo — APPROVED** [review]

**Pull request merged**
