### PR TITLE
[C-Api] fill dim (default 1)

### PR DESCRIPTION
**Pull request by jaeyun-jung**
When calling get-dimension(), fill remained dim - default dim is 1.

### CODE REVIEW

**Review by again4you — APPROVED** [review]
LGTM!

**Review by anyj0527 — APPROVED** [review]
LGTM ✔

**Review by niley7464 — APPROVED** [review]
LGTM :)
Thank you!

**Review by gichan-jang — APPROVED** [review]
LGTM

**Review by songgot — APPROVED** [review]
LGTM

**Comment by again4you** [comment]
This patch needs the Group Submission of QuickBuild.
So I will merge it even though some CI tests failed.

**Pull request merged**
