### PR TITLE
[Test] update flex-tensor caps

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Update caps for flexible tensor, old mime type for flex-tensor is removed.

Signed-off-by: Jaeyun <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
requires nnstreamer update (https://github.com/nnstreamer/nnstreamer/pull/3381)

**Review by myungjoo — APPROVED** [review]
LGTM

**Comment by jaeyun-jung** [comment]
requires https://github.com/nnstreamer/nnstreamer/pull/3418 to fix build error.

**Review by gichan-jang — APPROVED** [review]
LGTM

**Pull request merged**
