### PR TITLE
[Build/Tizen] dependency of tizen feature

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Code clean, update dependency for each tizen features.

### CODE REVIEW

**Review by anyj0527 — APPROVED** [review]
LGTM✔ Would this be cherry-picked in the lts branch?

**Comment by jaeyun-jung** [comment]
Discussion: should we cherry-pick this into lts branch?

**Comment by anyj0527** [comment]
Vote to cherry-pick when it's really needed in those branches.

**Review by myungjoo — APPROVED** [review]

**Review by songgot — APPROVED** [review]
LGTM

**Review by niley7464 — APPROVED** [review]
LGTM!

**Pull request merged**
